name: automatic-data-update

on:
  workflow_dispatch:
  schedule:
    - cron: '00 22 * * 2,6'

permissions:
  contents: write
  pull-requests: write
  models: read

jobs:
  automatic-data-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        cd leetcomp
        uv sync

    - name: Run complete data pipeline
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd leetcomp
        uv run python main.py

    - name: Commit files
      id: commit-files
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add .
        git diff --staged --exit-code || has_changes=$?
        if [ "$has_changes" == "1" ]; then
          echo "Changes detected, committing..."
          git commit -m "action: automated data refresh and cleanup"
        else
          echo "No changes to commit."
          echo "skipnext=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: (steps.commit-files.outputs.skipnext != 'true')
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update content
        title: "Automated PR to refresh data"
        body: "This is an automated pull request to refresh the data."
        branch: "data-refresh"
        delete-branch: true
        draft: false

    - name: Auto-merge PR
      if: (steps.commit-files.outputs.skipnext != 'true')
      uses: "pascalgn/automerge-action@v0.15.6"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        merge-method: squash
        pull-request-author: "github-actions[bot]"
        branch: "data-refresh"
